### ISSUE TITLE
can you merge this patch ?

### ISSUE THREAD

**Issue by youling257** [zefie/nxt_andx86_kernel#1]
https://github.com/burzumishi/linux-baytrail-flexx10
4.8 kernel tree Android x86?

**Comment by zefie** [comment]
I don't have this tablet anymore, but I checked out the repo and don't really see anything that kernel would offer that mine doesn't already, unless 4.8 fixes the random reboot issues.

**Comment by youling257** [comment]
nxt_andx86_kernel still no sound on some z3735f tablet,these patch may be can solve else z3735f problem. now, may be you need not care z3735f problem.

**Comment by youling257** [comment]
this new hifi file，https://drive.google.com/open?id=0B1HDhURlGNctSDRvMkVSWURsN2s
can you help me update alsa_cr.sh、alsa_cr_hp.sh、alsa_cr_spk.sh ？
https://groups.google.com/group/android-x86/attach/d1ffc290d6d56/alsa_bytcr_andx86.zip?part=0.1&authuser=0&view=1

@zefie
